services:
  api:
    build: .
    container_name: desbravacash-api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=desbravacash;Username=apisuer;Password=apipass
      - Jwt__Chave=teste
      - Jwt__Issuer=teste
      - Jwt__Audience=teste
      - Database__CertBase64=teste
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - desbravacash-network

  postgres:
    image: postgres:17-alpine
    container_name: desbravacash-postgres
    environment:
      POSTGRES_DB: desbravacash
      POSTGRES_USER: apisuer
      POSTGRES_PASSWORD: apipass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - desbravacash-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apisuer -d desbravacash"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  desbravacash-network:
    driver: bridge
