// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TigreDoMexico.DesbravaCash.Api.Infrastructure.Data;

#nullable disable

namespace TigreDoMexico.DesbravaCash.Api.Migrations
{
    [DbContext(typeof(DesbravaCashDbContext))]
    partial class DesbravaCashDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TigreDoMexico.DesbravaCash.Api.Domain.Transacoes.Models.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Valor")
                        .HasColumnType("integer")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("UnidadeId");

                    b.ToTable("transacao", (string)null);
                });

            modelBuilder.Entity("TigreDoMexico.DesbravaCash.Api.Domain.Unidades.Models.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("unidade", (string)null);
                });

            modelBuilder.Entity("TigreDoMexico.DesbravaCash.Api.Domain.Usuarios.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("cargo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("TigreDoMexico.DesbravaCash.Api.Domain.Transacoes.Models.Transacao", b =>
                {
                    b.HasOne("TigreDoMexico.DesbravaCash.Api.Domain.Usuarios.Models.Usuario", "CriadoPorUsuario")
                        .WithMany("Transacoes")
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TigreDoMexico.DesbravaCash.Api.Domain.Unidades.Models.Unidade", "Unidade")
                        .WithMany("Transacoes")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("TigreDoMexico.DesbravaCash.Api.Domain.Usuarios.Models.Usuario", b =>
                {
                    b.HasOne("TigreDoMexico.DesbravaCash.Api.Domain.Unidades.Models.Unidade", "Unidade")
                        .WithMany("Usuarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("TigreDoMexico.DesbravaCash.Api.Domain.Unidades.Models.Unidade", b =>
                {
                    b.Navigation("Transacoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TigreDoMexico.DesbravaCash.Api.Domain.Usuarios.Models.Usuario", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
