@API_URL = http://localhost:5101
@TOKEN = <bearer_token>

POST {{API_URL}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "telefone": "123456789",
  "senha": "senha123"
}

###

### Unidades

GET {{API_URL}}/api/unidades/dashboard
Authorization: Bearer {{TOKEN}}

###

GET {{API_URL}}/api/unidades
Authorization: Bearer {{TOKEN}}

###

### Transações

GET {{API_URL}}/api/transacoes
Authorization: Bearer {{TOKEN}}

###

GET {{API_URL}}/api/transacoes/pendentes
Authorization: Bearer {{TOKEN}}

###

POST {{API_URL}}/api/transacoes
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "unidadeId": "00000000-0000-0000-0000-000000000000",
  "valor": 100,
  "descricao": "Descrição da transação",
  "tipoTransacao": 1
}

###

PUT {{API_URL}}/api/transacoes/00000000-0000-0000-0000-000000000000/status
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "status": 1
}

###
