@API_URL = http://localhost:8080
@TOKEN = <bearer_token>

### Health Check

GET {{API_URL}}/api/health

### Versão da API

GET {{API_URL}}/api/version

### Autenticação

POST {{API_URL}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "telefone": "123456789",
  "senha": "senha123"
}

### Listar dados da Unidade

GET {{API_URL}}/api/unidades/dashboard
Authorization: Bearer {{TOKEN}}

### Obter lista de unidades

GET {{API_URL}}/api/unidades
Authorization: Bearer {{TOKEN}}

### Listar Transações pela Unidade

GET {{API_URL}}/api/transacoes
Authorization: Bearer {{TOKEN}}

### Listar todas as Transações Pendentes

GET {{API_URL}}/api/transacoes/pendentes
Authorization: Bearer {{TOKEN}}

### Cria uma nova Transação

POST {{API_URL}}/api/transacoes
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "unidadeId": "00000000-0000-0000-0000-000000000000",
  "valor": 100,
  "descricao": "Descrição da transação",
  "tipoTransacao": 1
}

### Atualiza o status de uma Transação

PUT {{API_URL}}/api/transacoes/00000000-0000-0000-0000-000000000000/status
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "status": 1
}

###
